export const flyoutTeams = [
  {
    id: 1,
    title: "Arizona Cardinals",
    logo: "cardinals.png",
    path: "./cardinals",
    cName: "submenu-item",
  },
  {
    id: 2,
    title: "Atlanta Falcons",
    logo: "falcons.png",
    path: "./falcons",
    cName: "submenu-item",
  },
  {
    id: 3,
    title: "Baltimore Ravens",
    logo: "ravens.png",
    path: "./ravens",
    cName: "submenu-item",
  },
  {
    id: 4,
    title: "Buffalo Bills",
    logo: "bills.png",
    path: "./bills",
    cName: "submenu-item",
  },
  {
    id: 5,
    title: "Carolina Panthers",
    logo: "panthers.png",
    path: "./panthers",
    cName: "submenu-item",
  },
  {
    id: 6,
    title: "Chicago Bears",
    logo: "bears.png",
    path: "./bears",
    cName: "submenu-item",
  },
  {
    id: 7,
    title: "Cincinnati Bengals",
    logo: "bengals.png",
    path: "./bengals",
    cName: "submenu-item",
  },
  {
    id: 8,
    title: "Cleveland Browns",
    logo: "browns.png",
    path: "./browns",
    cName: "submenu-item",
  },
  {
    id: 9,
    title: "Dallas Cowboys",
    logo: "cowboys.png",
    path: "./cowboys",
    cName: "submenu-item",
  },
  {
    id: 10,
    title: "Denver Broncos",
    logo: "broncos.png",
    path: "./broncos",
    cName: "submenu-item",
  },
  {
    id: 11,
    title: "Detroit Lions",
    logo: "lions.png",
    path: "./lions",
    cName: "submenu-item",
  },
  {
    id: 12,
    title: "Green Bay Packers",
    logo: "packers.png",
    path: "./packers",
    cName: "submenu-item",
  },
  {
    id: 13,
    title: "Houston Texans",
    logo: "texans.png",
    path: "./texans",
    cName: "submenu-item",
  },
  {
    id: 14,
    title: "Indianapolis Colts",
    logo: "colts.png",
    path: "./colts",
    cName: "submenu-item",
  },
  {
    id: 15,
    title: "Jacksonville Jaguars",
    logo: "jaguars.png",
    path: "./jaguars",
    cName: "submenu-item",
  },
  {
    id: 16,
    title: "Kansas City Chiefs",
    logo: "chiefs.png",
    path: "./chiefs",
    cName: "submenu-item",
  },
  {
    id: 17,
    title: "Las Vegas Raiders",
    logo: "raiders.png",
    path: "./raiders",
    cName: "submenu-item",
  },
  {
    id: 18,
    title: "Los Angeles Chargers",
    logo: "chargers.png",
    path: "./chargers",
    cName: "submenu-item",
  },
  {
    id: 19,
    title: "Los Angeles Rams",
    logo: "rams.png",
    path: "./rams",
    cName: "submenu-item",
  },
  {
    id: 20,
    title: "Miami Dolphins",
    logo: "dolphins.png",
    path: "./dolphins",
    cName: "submenu-item",
  },
  {
    id: 21,
    title: "Minnesota Vikings",
    logo: "vikings.png",
    path: "./vikings",
    cName: "submenu-item",
  },
  {
    id: 22,
    title: "New England Patriots",
    logo: "patriots.png",
    path: "./patriots",
    cName: "submenu-item",
  },
  {
    id: 23,
    title: "New Orleans Saints",
    logo: "saints.png",
    path: "./saints",
    cName: "submenu-item",
  },
  {
    id: 24,
    title: "New York Giants",
    logo: "giants.png",
    path: "./giants",
    cName: "submenu-item",
  },
  {
    id: 25,
    title: "New York Jets",
    logo: "jets.png",
    path: "./jets",
    cName: "submenu-item",
  },
  {
    id: 26,
    title: "Philadelphia Eagles",
    logo: "eagles.png",
    path: "./eagles",
    cName: "submenu-item",
  },
  {
    id: 27,
    title: "Pittsburgh Steelers",
    logo: "steelers.png",
    path: "./steelers",
    cName: "submenu-item",
  },
  {
    id: 28,
    title: "San Francisco 49ers",
    logo: "49ers.png",
    path: "./49ers",
    cName: "submenu-item",
  },
  {
    id: 29,
    title: "Seattle Seahawks",
    logo: "seahawks.png",
    path: "./seahawks",
    cName: "submenu-item",
  },
  {
    id: 30,
    title: "Tampa Bay Buccaneers",
    logo: "buccaneers.png",
    path: "./buccaneers",
    cName: "submenu-item",
  },
  {
    id: 31,
    title: "Tennessee Titans",
    logo: "titans.png",
    path: "./titans",
    cName: "submenu-item",
  },
  {
    id: 32,
    title: "Washington Commanders",
    logo: "commanders.png",
    path: "./commanders",
    cName: "submenu-item",
  },
];
